services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: false 

keycloak:
  server_url: 'http://keycloak:8080/'
  public_server_url: 'https://fis-nffadi-nomad.fisica.unimi.it/keycloak/'
  realm_name: nomad
  username: 'app'
  password: 'gomugomufruit'
  oasis: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/fairmat-nfdi/nomad-distro-template/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://fis-nffadi-nomad.fisica.unimi.it/api"
  maintainer_email: "elena.molteni@unimi.it"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1
